name: k6 Load Testing

on:
  workflow_dispatch:

jobs:

  test:
    name: Load testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: loadtest.js
