name: Deploy to FIrebase | Nonprod

on:
  push:
    branches: [ nonprod ]
  pull_request:
    branches: [ nonprod ]

  workflow_dispatch:

jobs:
  scan:
    name: Scan Depedency
    runs-on: ubuntu-latest
    container:
      image: 244342/node-jfrog:14.17.3-buster
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Import jfrog server token
        run: jfrog c import ${{ secrets.JFROG_SERVER_TOKEN }}
      
      - name: Test JFROG connection
        run: jfrog rt ping
      
      - name: Scan NPM depedency
        run: jfrog xr audit-npm

  build:
    name: Build Love Meter Project
    runs-on: ubuntu-latest
    container:
      image: node:14.17.3-buster

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Depedency
        run: |
          npm install -g @vue/cli
          npm install

      - name: Build Project
        run: npm run build
      
      - name: Save to JFROG
        run: |
          cd dist
          tar -C $(pwd) -cf lovemeter-${GITHUB_RUN_NUMBER}.tar.gz *
          curl -k -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} -T lovemeter-${GITHUB_RUN_NUMBER}.tar.gz "https://beningc.jfrog.io/artifactory/lovemeter/webapp/nonprod/lovemeter-${GITHUB_RUN_NUMBER}.tar.gz"
      
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
